name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        id: snyk
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects
          
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Create zip if code is secure
        #if: steps.snyk.conclusion != 'success'
        uses: ihiroky/archive-action@v1
        with:
          root_dir: $GITHUB_WORKSPACE/my-directory
          file_path: secure_code.zip

      - name: Upload zip to artifac
        uses: actions/upload-artifact@v2
        with:
          name: zip-secure-code-artifact
          path: secure_code.zip
